<?php
/**
 * DiscoveryEntRankRankAlbumTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * DiscoveryEntRankRankAlbumTest Class Doc Comment
 *
 * @category    Class
 * @description DiscoveryEntRankRankAlbum
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DiscoveryEntRankRankAlbumTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DiscoveryEntRankRankAlbum"
     */
    public function testDiscoveryEntRankRankAlbum()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "name_en"
     */
    public function testPropertyNameEn()
    {
    }

    /**
     * Test attribute "poster"
     */
    public function testPropertyPoster()
    {
    }

    /**
     * Test attribute "release_date"
     */
    public function testPropertyReleaseDate()
    {
    }

    /**
     * Test attribute "hot"
     */
    public function testPropertyHot()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "maoyan_id"
     */
    public function testPropertyMaoyanId()
    {
    }

    /**
     * Test attribute "areas"
     */
    public function testPropertyAreas()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "directors"
     */
    public function testPropertyDirectors()
    {
    }

    /**
     * Test attribute "actors"
     */
    public function testPropertyActors()
    {
    }

    /**
     * Test attribute "influence_hot"
     */
    public function testPropertyInfluenceHot()
    {
    }

    /**
     * Test attribute "discussion_hot"
     */
    public function testPropertyDiscussionHot()
    {
    }

    /**
     * Test attribute "topic_hot"
     */
    public function testPropertyTopicHot()
    {
    }

    /**
     * Test attribute "search_hot"
     */
    public function testPropertySearchHot()
    {
    }
}
