<?php
/**
 * DouyinPayDouyinPayInlineResponse2001DataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * DouyinPayDouyinPayInlineResponse2001DataTest Class Doc Comment
 *
 * @category    Class
 * @description DouyinPayDouyinPayInlineResponse2001Data
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DouyinPayDouyinPayInlineResponse2001DataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DouyinPayDouyinPayInlineResponse2001Data"
     */
    public function testDouyinPayDouyinPayInlineResponse2001Data()
    {
    }

    /**
     * Test attribute "ret_code"
     */
    public function testPropertyRetCode()
    {
    }

    /**
     * Test attribute "ret_msg"
     */
    public function testPropertyRetMsg()
    {
    }

    /**
     * Test attribute "sub_code"
     */
    public function testPropertySubCode()
    {
    }

    /**
     * Test attribute "sub_msg"
     */
    public function testPropertySubMsg()
    {
    }

    /**
     * Test attribute "order_status"
     */
    public function testPropertyOrderStatus()
    {
    }

    /**
     * Test attribute "pay_order_no"
     */
    public function testPropertyPayOrderNo()
    {
    }

    /**
     * Test attribute "biz_order_no"
     */
    public function testPropertyBizOrderNo()
    {
    }

    /**
     * Test attribute "remark"
     */
    public function testPropertyRemark()
    {
    }

    /**
     * Test attribute "order_name"
     */
    public function testPropertyOrderName()
    {
    }

    /**
     * Test attribute "order_desc"
     */
    public function testPropertyOrderDesc()
    {
    }

    /**
     * Test attribute "pay_create_time"
     */
    public function testPropertyPayCreateTime()
    {
    }

    /**
     * Test attribute "pay_finish_time"
     */
    public function testPropertyPayFinishTime()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }
}
