<?php
/**
 * DouyinPayDouyinPayBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * DouyinPayDouyinPayBodyTest Class Doc Comment
 *
 * @category    Class
 * @description DouyinPayDouyinPayBody
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DouyinPayDouyinPayBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DouyinPayDouyinPayBody"
     */
    public function testDouyinPayDouyinPayBody()
    {
    }

    /**
     * Test attribute "merchant_id"
     */
    public function testPropertyMerchantId()
    {
    }

    /**
     * Test attribute "live_id"
     */
    public function testPropertyLiveId()
    {
    }

    /**
     * Test attribute "biz_order_no"
     */
    public function testPropertyBizOrderNo()
    {
    }

    /**
     * Test attribute "trans_code"
     */
    public function testPropertyTransCode()
    {
    }

    /**
     * Test attribute "order_name"
     */
    public function testPropertyOrderName()
    {
    }

    /**
     * Test attribute "order_desc"
     */
    public function testPropertyOrderDesc()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "remark"
     */
    public function testPropertyRemark()
    {
    }
}
