<?php
/**
 * EnterpriseGrouponGrouponGrouponSaveGrouponItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 创建团购活动
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * EnterpriseGrouponGrouponGrouponSaveGrouponItemTest Class Doc Comment
 *
 * @category    Class
 * @description EnterpriseGrouponGrouponGrouponSaveGrouponItem
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EnterpriseGrouponGrouponGrouponSaveGrouponItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EnterpriseGrouponGrouponGrouponSaveGrouponItem"
     */
    public function testEnterpriseGrouponGrouponGrouponSaveGrouponItem()
    {
    }

    /**
     * Test attribute "groupon_id"
     */
    public function testPropertyGrouponId()
    {
    }

    /**
     * Test attribute "use_type"
     */
    public function testPropertyUseType()
    {
    }

    /**
     * Test attribute "code_type"
     */
    public function testPropertyCodeType()
    {
    }

    /**
     * Test attribute "merchant_name"
     */
    public function testPropertyMerchantName()
    {
    }

    /**
     * Test attribute "service_number"
     */
    public function testPropertyServiceNumber()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "cover_images"
     */
    public function testPropertyCoverImages()
    {
    }

    /**
     * Test attribute "original_amount"
     */
    public function testPropertyOriginalAmount()
    {
    }

    /**
     * Test attribute "actual_amount"
     */
    public function testPropertyActualAmount()
    {
    }

    /**
     * Test attribute "notification"
     */
    public function testPropertyNotification()
    {
    }

    /**
     * Test attribute "order_limit"
     */
    public function testPropertyOrderLimit()
    {
    }

    /**
     * Test attribute "stock"
     */
    public function testPropertyStock()
    {
    }

    /**
     * Test attribute "poi_ids"
     */
    public function testPropertyPoiIds()
    {
    }

    /**
     * Test attribute "groupon_goods"
     */
    public function testPropertyGrouponGoods()
    {
    }

    /**
     * Test attribute "start_time"
     */
    public function testPropertyStartTime()
    {
    }

    /**
     * Test attribute "end_time"
     */
    public function testPropertyEndTime()
    {
    }

    /**
     * Test attribute "h5_url"
     */
    public function testPropertyH5Url()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "sold_count"
     */
    public function testPropertySoldCount()
    {
    }

    /**
     * Test attribute "audit_msg"
     */
    public function testPropertyAuditMsg()
    {
    }
}
