<?php
/**
 * EnterpriseGrouponGrouponCommonGrouponEventOrderInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 团购活动事件回调
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * EnterpriseGrouponGrouponCommonGrouponEventOrderInfoTest Class Doc Comment
 *
 * @category    Class
 * @description EnterpriseGrouponGrouponCommonGrouponEventOrderInfo
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EnterpriseGrouponGrouponCommonGrouponEventOrderInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EnterpriseGrouponGrouponCommonGrouponEventOrderInfo"
     */
    public function testEnterpriseGrouponGrouponCommonGrouponEventOrderInfo()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "channel"
     */
    public function testPropertyChannel()
    {
    }

    /**
     * Test attribute "buyer_open_id"
     */
    public function testPropertyBuyerOpenId()
    {
    }

    /**
     * Test attribute "original_amount"
     */
    public function testPropertyOriginalAmount()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "refund_amount"
     */
    public function testPropertyRefundAmount()
    {
    }

    /**
     * Test attribute "settle_amount"
     */
    public function testPropertySettleAmount()
    {
    }

    /**
     * Test attribute "item_count"
     */
    public function testPropertyItemCount()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "create_time"
     */
    public function testPropertyCreateTime()
    {
    }

    /**
     * Test attribute "pay_time"
     */
    public function testPropertyPayTime()
    {
    }

    /**
     * Test attribute "refund_time"
     */
    public function testPropertyRefundTime()
    {
    }

    /**
     * Test attribute "codes"
     */
    public function testPropertyCodes()
    {
    }
}
