<?php
/**
 * EnterpriseGrouponGrouponCodeCodeVerificationBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 券码核销
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * EnterpriseGrouponGrouponCodeCodeVerificationBodyTest Class Doc Comment
 *
 * @category    Class
 * @description EnterpriseGrouponGrouponCodeCodeVerificationBody
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EnterpriseGrouponGrouponCodeCodeVerificationBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EnterpriseGrouponGrouponCodeCodeVerificationBody"
     */
    public function testEnterpriseGrouponGrouponCodeCodeVerificationBody()
    {
    }

    /**
     * Test attribute "groupon_id"
     */
    public function testPropertyGrouponId()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }
}
