<?php
/**
 * EnterpriseGrouponGrouponCommonGrouponEventOrderStatusChangeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 团购活动事件回调
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * EnterpriseGrouponGrouponCommonGrouponEventOrderStatusChangeTest Class Doc Comment
 *
 * @category    Class
 * @description 卷码状态变更时间同步
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EnterpriseGrouponGrouponCommonGrouponEventOrderStatusChangeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EnterpriseGrouponGrouponCommonGrouponEventOrderStatusChange"
     */
    public function testEnterpriseGrouponGrouponCommonGrouponEventOrderStatusChange()
    {
    }

    /**
     * Test attribute "event"
     */
    public function testPropertyEvent()
    {
    }

    /**
     * Test attribute "from_user_id"
     */
    public function testPropertyFromUserId()
    {
    }

    /**
     * Test attribute "client_key"
     */
    public function testPropertyClientKey()
    {
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
    }
}
