<?php
/**
 * EnterpriseImEnterpriseImBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 企业号发送消息
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * EnterpriseImEnterpriseImBodyTest Class Doc Comment
 *
 * @category    Class
 * @description EnterpriseImEnterpriseImBody
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EnterpriseImEnterpriseImBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EnterpriseImEnterpriseImBody"
     */
    public function testEnterpriseImEnterpriseImBody()
    {
    }

    /**
     * Test attribute "to_user_id"
     */
    public function testPropertyToUserId()
    {
    }

    /**
     * Test attribute "message_type"
     */
    public function testPropertyMessageType()
    {
    }

    /**
     * Test attribute "persona_id"
     */
    public function testPropertyPersonaId()
    {
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
    }

    /**
     * Test attribute "client_msg_id"
     */
    public function testPropertyClientMsgId()
    {
    }
}
