<?php
/**
 * ExternalDataPoiExternalDataPoiExternalPoiBillboardTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * ExternalDataPoiExternalDataPoiExternalPoiBillboardTest Class Doc Comment
 *
 * @category    Class
 * @description ExternalDataPoiExternalDataPoiExternalPoiBillboard
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExternalDataPoiExternalDataPoiExternalPoiBillboardTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ExternalDataPoiExternalDataPoiExternalPoiBillboard"
     */
    public function testExternalDataPoiExternalDataPoiExternalPoiBillboard()
    {
    }

    /**
     * Test attribute "poi_id"
     */
    public function testPropertyPoiId()
    {
    }

    /**
     * Test attribute "poi_name"
     */
    public function testPropertyPoiName()
    {
    }

    /**
     * Test attribute "score"
     */
    public function testPropertyScore()
    {
    }

    /**
     * Test attribute "rank"
     */
    public function testPropertyRank()
    {
    }
}
