<?php
/**
 * ExternalDataItemExternalDataItemExternalItemBaseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * ExternalDataItemExternalDataItemExternalItemBaseTest Class Doc Comment
 *
 * @category    Class
 * @description ExternalDataItemExternalDataItemExternalItemBase
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExternalDataItemExternalDataItemExternalItemBaseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ExternalDataItemExternalDataItemExternalItemBase"
     */
    public function testExternalDataItemExternalDataItemExternalItemBase()
    {
    }

    /**
     * Test attribute "total_play"
     */
    public function testPropertyTotalPlay()
    {
    }

    /**
     * Test attribute "total_like"
     */
    public function testPropertyTotalLike()
    {
    }

    /**
     * Test attribute "total_comment"
     */
    public function testPropertyTotalComment()
    {
    }

    /**
     * Test attribute "total_share"
     */
    public function testPropertyTotalShare()
    {
    }

    /**
     * Test attribute "avg_play_duration"
     */
    public function testPropertyAvgPlayDuration()
    {
    }
}
