<?php
/**
 * FansDataFansDataFansProfileFlowContributionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 获取用户的粉丝数据
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * FansDataFansDataFansProfileFlowContributionTest Class Doc Comment
 *
 * @category    Class
 * @description FansDataFansDataFansProfileFlowContribution
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FansDataFansDataFansProfileFlowContributionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FansDataFansDataFansProfileFlowContribution"
     */
    public function testFansDataFansDataFansProfileFlowContribution()
    {
    }

    /**
     * Test attribute "flow"
     */
    public function testPropertyFlow()
    {
    }

    /**
     * Test attribute "fans_sum"
     */
    public function testPropertyFansSum()
    {
    }

    /**
     * Test attribute "all_sum"
     */
    public function testPropertyAllSum()
    {
    }
}
