<?php
/**
 * MusicCollectionListMusicCollectionListInlineResponse200DataListTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 仅对内提供
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * MusicCollectionListMusicCollectionListInlineResponse200DataListTest Class Doc Comment
 *
 * @category    Class
 * @description MusicCollectionListMusicCollectionListInlineResponse200DataList
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MusicCollectionListMusicCollectionListInlineResponse200DataListTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MusicCollectionListMusicCollectionListInlineResponse200DataList"
     */
    public function testMusicCollectionListMusicCollectionListInlineResponse200DataList()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "cover"
     */
    public function testPropertyCover()
    {
    }

    /**
     * Test attribute "author"
     */
    public function testPropertyAuthor()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "isrc"
     */
    public function testPropertyIsrc()
    {
    }

    /**
     * Test attribute "meta_song_id"
     */
    public function testPropertyMetaSongId()
    {
    }
}
