<?php
/**
 * PoiOrderSyncOrderSyncBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * PoiOrderSyncOrderSyncBodyTest Class Doc Comment
 *
 * @category    Class
 * @description PoiOrderSyncOrderSyncBody
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PoiOrderSyncOrderSyncBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PoiOrderSyncOrderSyncBody"
     */
    public function testPoiOrderSyncOrderSyncBody()
    {
    }

    /**
     * Test attribute "mini_app"
     */
    public function testPropertyMiniApp()
    {
    }

    /**
     * Test attribute "order_type"
     */
    public function testPropertyOrderType()
    {
    }

    /**
     * Test attribute "date_time"
     */
    public function testPropertyDateTime()
    {
    }

    /**
     * Test attribute "order_detail"
     */
    public function testPropertyOrderDetail()
    {
    }

    /**
     * Test attribute "ext_shop_info"
     */
    public function testPropertyExtShopInfo()
    {
    }
}
