<?php
/**
 * PoiProductProductSpuAttributesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * PoiProductProductSpuAttributesTest Class Doc Comment
 *
 * @category    Class
 * @description SPU属性字段
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PoiProductProductSpuAttributesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PoiProductProductSpuAttributes"
     */
    public function testPoiProductProductSpuAttributes()
    {
    }

    /**
     * Test attribute "_1201"
     */
    public function testProperty1201()
    {
    }

    /**
     * Test attribute "_1202"
     */
    public function testProperty1202()
    {
    }

    /**
     * Test attribute "_1203"
     */
    public function testProperty1203()
    {
    }

    /**
     * Test attribute "_1204"
     */
    public function testProperty1204()
    {
    }

    /**
     * Test attribute "_1205"
     */
    public function testProperty1205()
    {
    }

    /**
     * Test attribute "_1206"
     */
    public function testProperty1206()
    {
    }

    /**
     * Test attribute "_1207"
     */
    public function testProperty1207()
    {
    }

    /**
     * Test attribute "_1208"
     */
    public function testProperty1208()
    {
    }

    /**
     * Test attribute "_1209"
     */
    public function testProperty1209()
    {
    }

    /**
     * Test attribute "_1210"
     */
    public function testProperty1210()
    {
    }

    /**
     * Test attribute "_1211"
     */
    public function testProperty1211()
    {
    }

    /**
     * Test attribute "_1212"
     */
    public function testProperty1212()
    {
    }

    /**
     * Test attribute "_1213"
     */
    public function testProperty1213()
    {
    }

    /**
     * Test attribute "_1214"
     */
    public function testProperty1214()
    {
    }

    /**
     * Test attribute "_90201"
     */
    public function testProperty90201()
    {
    }

    /**
     * Test attribute "_90202"
     */
    public function testProperty90202()
    {
    }

    /**
     * Test attribute "_90203"
     */
    public function testProperty90203()
    {
    }

    /**
     * Test attribute "_90204"
     */
    public function testProperty90204()
    {
    }

    /**
     * Test attribute "_90205"
     */
    public function testProperty90205()
    {
    }

    /**
     * Test attribute "_4101"
     */
    public function testProperty4101()
    {
    }

    /**
     * Test attribute "_9101"
     */
    public function testProperty9101()
    {
    }
}
