<?php
/**
 * PoiProductProductSpuAttributes9101Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * PoiProductProductSpuAttributes9101Test Class Doc Comment
 *
 * @category    Class
 * @description 团购劵属性
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PoiProductProductSpuAttributes9101Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PoiProductProductSpuAttributes9101"
     */
    public function testPoiProductProductSpuAttributes9101()
    {
    }

    /**
     * Test attribute "market_price"
     */
    public function testPropertyMarketPrice()
    {
    }

    /**
     * Test attribute "img"
     */
    public function testPropertyImg()
    {
    }

    /**
     * Test attribute "sub_title"
     */
    public function testPropertySubTitle()
    {
    }

    /**
     * Test attribute "tag_list"
     */
    public function testPropertyTagList()
    {
    }
}
