<?php
/**
 * PoiProductProductSpuAttributes4101DetailEntryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * PoiProductProductSpuAttributes4101DetailEntryTest Class Doc Comment
 *
 * @category    Class
 * @description 详情页链接信息
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PoiProductProductSpuAttributes4101DetailEntryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PoiProductProductSpuAttributes4101DetailEntry"
     */
    public function testPoiProductProductSpuAttributes4101DetailEntry()
    {
    }

    /**
     * Test attribute "schema_type"
     */
    public function testPropertySchemaType()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "platform_source"
     */
    public function testPropertyPlatformSource()
    {
    }

    /**
     * Test attribute "platform_name"
     */
    public function testPropertyPlatformName()
    {
    }

    /**
     * Test attribute "is_test"
     */
    public function testPropertyIsTest()
    {
    }
}
