<?php
/**
 * PoiSupplierSupplierSupplierAttributesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * PoiSupplierSupplierSupplierAttributesTest Class Doc Comment
 *
 * @category    Class
 * @description 店铺属性字段，编号规则：垂直行业 1xxx-酒店民宿 2xxx-餐饮 3xxx-景区 通用属性-9yxxx
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PoiSupplierSupplierSupplierAttributesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PoiSupplierSupplierSupplierAttributes"
     */
    public function testPoiSupplierSupplierSupplierAttributes()
    {
    }

    /**
     * Test attribute "_1101"
     */
    public function testProperty1101()
    {
    }

    /**
     * Test attribute "_1102"
     */
    public function testProperty1102()
    {
    }

    /**
     * Test attribute "_1103"
     */
    public function testProperty1103()
    {
    }

    /**
     * Test attribute "_1104"
     */
    public function testProperty1104()
    {
    }

    /**
     * Test attribute "_1105"
     */
    public function testProperty1105()
    {
    }

    /**
     * Test attribute "_3101"
     */
    public function testProperty3101()
    {
    }
}
