<?php
/**
 * VideoCreateAwemeCreateBody1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * VideoCreateAwemeCreateBody1Test Class Doc Comment
 *
 * @category    Class
 * @description VideoCreateAwemeCreateBody1
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VideoCreateAwemeCreateBody1Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VideoCreateAwemeCreateBody1"
     */
    public function testVideoCreateAwemeCreateBody1()
    {
    }

    /**
     * Test attribute "video_id"
     */
    public function testPropertyVideoId()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }

    /**
     * Test attribute "poi_id"
     */
    public function testPropertyPoiId()
    {
    }

    /**
     * Test attribute "poi_name"
     */
    public function testPropertyPoiName()
    {
    }

    /**
     * Test attribute "micro_app_id"
     */
    public function testPropertyMicroAppId()
    {
    }

    /**
     * Test attribute "micro_app_title"
     */
    public function testPropertyMicroAppTitle()
    {
    }

    /**
     * Test attribute "micro_app_url"
     */
    public function testPropertyMicroAppUrl()
    {
    }

    /**
     * Test attribute "article_id"
     */
    public function testPropertyArticleId()
    {
    }

    /**
     * Test attribute "article_title"
     */
    public function testPropertyArticleTitle()
    {
    }

    /**
     * Test attribute "timeliness_label"
     */
    public function testPropertyTimelinessLabel()
    {
    }

    /**
     * Test attribute "timeliness_keyword"
     */
    public function testPropertyTimelinessKeyword()
    {
    }

    /**
     * Test attribute "game_id"
     */
    public function testPropertyGameId()
    {
    }

    /**
     * Test attribute "game_content"
     */
    public function testPropertyGameContent()
    {
    }

    /**
     * Test attribute "cover_tsp"
     */
    public function testPropertyCoverTsp()
    {
    }

    /**
     * Test attribute "at_users"
     */
    public function testPropertyAtUsers()
    {
    }
}
