<?php
/**
 * XiguaVideoCreateBody1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * XiguaVideoCreateBody1Test Class Doc Comment
 *
 * @category    Class
 * @description XiguaVideoCreateBody1
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class XiguaVideoCreateBody1Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "XiguaVideoCreateBody1"
     */
    public function testXiguaVideoCreateBody1()
    {
    }

    /**
     * Test attribute "video_id"
     */
    public function testPropertyVideoId()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }

    /**
     * Test attribute "praise"
     */
    public function testPropertyPraise()
    {
    }

    /**
     * Test attribute "claim_origin"
     */
    public function testPropertyClaimOrigin()
    {
    }

    /**
     * Test attribute "abstract"
     */
    public function testPropertyAbstract()
    {
    }

    /**
     * Test attribute "cover_tsp"
     */
    public function testPropertyCoverTsp()
    {
    }
}
