<?php
/**
 * XiguaDataVideoDataToutiaoVideoStatisticsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 通过西瓜视频id批量获取已分享视频数据信息
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace swagger_client;

/**
 * XiguaDataVideoDataToutiaoVideoStatisticsTest Class Doc Comment
 *
 * @category    Class
 * @description 统计数据
 * @package     swagger_client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class XiguaDataVideoDataToutiaoVideoStatisticsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "XiguaDataVideoDataToutiaoVideoStatistics"
     */
    public function testXiguaDataVideoDataToutiaoVideoStatistics()
    {
    }

    /**
     * Test attribute "comment_count"
     */
    public function testPropertyCommentCount()
    {
    }

    /**
     * Test attribute "digg_count"
     */
    public function testPropertyDiggCount()
    {
    }

    /**
     * Test attribute "play_count"
     */
    public function testPropertyPlayCount()
    {
    }

    /**
     * Test attribute "share_count"
     */
    public function testPropertyShareCount()
    {
    }

    /**
     * Test attribute "forward_count"
     */
    public function testPropertyForwardCount()
    {
    }
}
