<?php
/**
 * DataExternalItemApiTest
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace swagger_client;

use swagger_client\Configuration;
use swagger_client\ApiException;
use swagger_client\ObjectSerializer;

/**
 * DataExternalItemApiTest Class Doc Comment
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DataExternalItemApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for dataExternalItemBaseGet
     *
     * 获取视频基础数据.
     *
     */
    public function testDataExternalItemBaseGet()
    {
    }

    /**
     * Test case for dataExternalItemCommentGet
     *
     * 获取视频评论数据.
     *
     */
    public function testDataExternalItemCommentGet()
    {
    }

    /**
     * Test case for dataExternalItemLikeGet
     *
     * 获取视频点赞数据.
     *
     */
    public function testDataExternalItemLikeGet()
    {
    }

    /**
     * Test case for dataExternalItemPlayGet
     *
     * 获取视频播放数据.
     *
     */
    public function testDataExternalItemPlayGet()
    {
    }

    /**
     * Test case for dataExternalItemShareGet
     *
     * 获取视频分享数据.
     *
     */
    public function testDataExternalItemShareGet()
    {
    }
}
