<?php
/**
 * DataExternalUserApiTest
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace swagger_client;

use swagger_client\Configuration;
use swagger_client\ApiException;
use swagger_client\ObjectSerializer;

/**
 * DataExternalUserApiTest Class Doc Comment
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DataExternalUserApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for dataExternalUserCommentGet
     *
     * 获取用户评论数.
     *
     */
    public function testDataExternalUserCommentGet()
    {
    }

    /**
     * Test case for dataExternalUserFansGet
     *
     * 获取用户粉丝数.
     *
     */
    public function testDataExternalUserFansGet()
    {
    }

    /**
     * Test case for dataExternalUserItemGet
     *
     * 获取用户视频情况.
     *
     */
    public function testDataExternalUserItemGet()
    {
    }

    /**
     * Test case for dataExternalUserLikeGet
     *
     * 获取用户点赞数.
     *
     */
    public function testDataExternalUserLikeGet()
    {
    }

    /**
     * Test case for dataExternalUserProfileGet
     *
     * 获取用户主页访问数.
     *
     */
    public function testDataExternalUserProfileGet()
    {
    }

    /**
     * Test case for dataExternalUserShareGet
     *
     * 获取用户分享数.
     *
     */
    public function testDataExternalUserShareGet()
    {
    }
}
