<?php
/**
 * EnterpriseLeadsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 企业号意向用户管理
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace swagger_client;

use swagger_client\Configuration;
use swagger_client\ApiException;
use swagger_client\ObjectSerializer;

/**
 * EnterpriseLeadsApiTest Class Doc Comment
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EnterpriseLeadsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for enterpriseLeadsTagCreatePost
     *
     * 创建标签.
     *
     */
    public function testEnterpriseLeadsTagCreatePost()
    {
    }

    /**
     * Test case for enterpriseLeadsTagDeletePost
     *
     * 删除标签.
     *
     */
    public function testEnterpriseLeadsTagDeletePost()
    {
    }

    /**
     * Test case for enterpriseLeadsTagListGet
     *
     * 获取标签列表.
     *
     */
    public function testEnterpriseLeadsTagListGet()
    {
    }

    /**
     * Test case for enterpriseLeadsTagUpdatePost
     *
     * 编辑标签.
     *
     */
    public function testEnterpriseLeadsTagUpdatePost()
    {
    }

    /**
     * Test case for enterpriseLeadsTagUserListGet
     *
     * 获取打标签的用户列表.
     *
     */
    public function testEnterpriseLeadsTagUserListGet()
    {
    }

    /**
     * Test case for enterpriseLeadsTagUserUpdatePost
     *
     * 给用户设置标签.
     *
     */
    public function testEnterpriseLeadsTagUserUpdatePost()
    {
    }

    /**
     * Test case for enterpriseLeadsUserActionListGet
     *
     * 获取意向用户互动记录.
     *
     */
    public function testEnterpriseLeadsUserActionListGet()
    {
    }

    /**
     * Test case for enterpriseLeadsUserDetailGet
     *
     * 获取意向用户详情.
     *
     */
    public function testEnterpriseLeadsUserDetailGet()
    {
    }

    /**
     * Test case for enterpriseLeadsUserListGet
     *
     * 获取意向用户列表.
     *
     */
    public function testEnterpriseLeadsUserListGet()
    {
    }
}
