<?php
/**
 * PoiSupplierApiTest
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace swagger_client;

use swagger_client\Configuration;
use swagger_client\ApiException;
use swagger_client\ObjectSerializer;

/**
 * PoiSupplierApiTest Class Doc Comment
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PoiSupplierApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for poiQueryGet
     *
     * 获取抖音POI ID.
     *
     */
    public function testPoiQueryGet()
    {
    }

    /**
     * Test case for poiSupplierMatchPost
     *
     * 店铺匹配.
     *
     */
    public function testPoiSupplierMatchPost()
    {
    }

    /**
     * Test case for poiSupplierMatchQueryGet
     *
     * 店铺匹配结果查询.
     *
     */
    public function testPoiSupplierMatchQueryGet()
    {
    }

    /**
     * Test case for poiSupplierQueryGet
     *
     * 查询店铺.
     *
     */
    public function testPoiSupplierQueryGet()
    {
    }

    /**
     * Test case for poiSupplierSyncPost
     *
     * 商铺同步.
     *
     */
    public function testPoiSupplierSyncPost()
    {
    }
}
