<?php
/**
 * PoiSpuApiTest
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace swagger_client;

use swagger_client\Configuration;
use swagger_client\ApiException;
use swagger_client\ObjectSerializer;

/**
 * PoiSpuApiTest Class Doc Comment
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PoiSpuApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for poiSkuSyncPost
     *
     * SKU同步.
     *
     */
    public function testPoiSkuSyncPost()
    {
    }

    /**
     * Test case for poiSpuQueryGet
     *
     * 查询SPU.
     *
     */
    public function testPoiSpuQueryGet()
    {
    }

    /**
     * Test case for poiSpuSyncPost
     *
     * SPU同步.
     *
     */
    public function testPoiSpuSyncPost()
    {
    }
}
