<?php
/**
 * VideoPublishApiTest
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace swagger_client;

use swagger_client\Configuration;
use swagger_client\ApiException;
use swagger_client\ObjectSerializer;

/**
 * VideoPublishApiTest Class Doc Comment
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VideoPublishApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for videoCreatePost
     *
     * 创建抖音视频.
     *
     */
    public function testVideoCreatePost()
    {
    }

    /**
     * Test case for videoPartCompletePost
     *
     * 完成上传.
     *
     */
    public function testVideoPartCompletePost()
    {
    }

    /**
     * Test case for videoPartInitPost
     *
     * 初始化上传.
     *
     */
    public function testVideoPartInitPost()
    {
    }

    /**
     * Test case for videoPartUploadPost
     *
     * 上传视频分片到文件服务器.
     *
     */
    public function testVideoPartUploadPost()
    {
    }

    /**
     * Test case for videoUploadPost
     *
     * 上传视频到文件服务器.
     *
     */
    public function testVideoUploadPost()
    {
    }
}
