<?php
/**
 * XiguaVideoPublishApiTest
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace swagger_client;

use swagger_client\Configuration;
use swagger_client\ApiException;
use swagger_client\ObjectSerializer;

/**
 * XiguaVideoPublishApiTest Class Doc Comment
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class XiguaVideoPublishApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for xiguaVideoCreatePost
     *
     * 创建西瓜视频.
     *
     */
    public function testXiguaVideoCreatePost()
    {
    }

    /**
     * Test case for xiguaVideoPartCompletePost
     *
     * 完成上传.
     *
     */
    public function testXiguaVideoPartCompletePost()
    {
    }

    /**
     * Test case for xiguaVideoPartInitPost
     *
     * 初始化上传.
     *
     */
    public function testXiguaVideoPartInitPost()
    {
    }

    /**
     * Test case for xiguaVideoPartUploadPost
     *
     * 上传视频分片到文件服务器.
     *
     */
    public function testXiguaVideoPartUploadPost()
    {
    }

    /**
     * Test case for xiguaVideoUploadPost
     *
     * 上传视频到文件服务器.
     *
     */
    public function testXiguaVideoUploadPost()
    {
    }
}
